---
#   _____                __  _         ______     _  _  _               
#  / ____|              / _|(_)       |  ____|   | |(_)| |              
# | |      ___   _ __  | |_  _   __ _ | |__    __| | _ | |_  ___   _ __ 
# | |     / _ \ | '_ \ |  _|| | / _` ||  __|  / _` || || __|/ _ \ | '__|
# | |____| (_) || | | || |  | || (_| || |____| (_| || || |_| (_) || |   
#  \_____|\___/ |_| |_||_|  |_| \__, ||______|\__,_||_| \__|\___/ |_|   
#                                __/ |                                  
#                               |___/                                   
# Too lazy to go to a folder and edit configs? Do it directly in game !

# Add here all the configs with eg confidential data such as passwords for databases that should not be opened ingame
Forbidden configs: [
    "ConfigEditor/config.yml",
]
...